---
- name: VECTOR | download Vector distr
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
    dest: "./vector-{{ vector_version }}.rpm"
    mode: 0644

- name: VECTOR| Install Vector 
  become: true
  ansible.builtin.yum:
    name:
      - vector-{{ vector_version }}.rpm
    
- name: VECTOR | creating vector config
  become: true
  ansible.builtin.file:
    path: "{{ vector_conf_dir }}"
    state: directory
    mode: 0644

- name: VECTOR | apply vector template
  become: true
  ansible.builtin.template:
    src: "templates/vector.j2"
    dest: "{{ vector_conf_dir }}/vector.yml"
    mode: "0644"
  notify: restart-vector-service

- name: Flush handlers
  ansible.legacy.meta: flush_handlers
  notify: restart-vector-service

- name: VECTOR | Create systemd
  become: true
  ansible.builtin.template:
    src: vector.service.j2
    dest: /etc/systemd/system/vector.service
    mode: 0644

- name: VECTOR | start vector service
  become: true
  ansible.builtin.systemd:
    name: vector
    state: started
    daemon_reload: true
