---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: centos7
    pre_build_image: true
  - name: oraclelinux
    image: oraclelinux:8
    pre_build_image: true
  - name: ubuntu
    image: ubuntu:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible